@startuml
|Kunde|
start
:Åbner hjemmeside;
:Indtaster mål på carport;
:Sender forespørgsel;

|Carport Shop|
:Modtager kundeinput;
:Validerer mål på carport;
:Sender forespørgsel til sælger;

|Sælger|
:Åbner forespørgsel;
:Kontakter kunde ved behov;
:Indtaster ændringer (hvis nogle) i system;

|Lager System|
:Modtager mål fra sælger;
:Beregner styklisten;
:Sender styklisten til sælger;

|Sælger|
:Udarbejder tilbud manuelt;

|FogMail System|
:Modtager tilbud;
:Sender tilbud til kunde;

|Kunde|
:Modtager tilbud;
:Accepterer tilbud;

|Sælger|
:Modtager accept;
:Opretter ordre manuelt;

|FogMail System|
:Sender ordrebekræftelse;

|Kunde|
:Modtager ordrebekræftelse;
stop
@enduml
