@startuml
|Kunde|
start
:Åbner hjemmeside;

repeat
:Indtaster mål på carport;

    |Carport Shop|
    :Modtager kundeinput;
    :Validerer mål på carport;

    |Kunde|
    :Modtager 2D tegning;

repeat while (Accepter Tegning) is (Nej) not  (Ja)

|Carport Shop|
:Sender forespørgsel til sælger;

|Sælger|
:Åbner forespørgsel;
:Kontakter kunde ved behov;
:Indtaster ændringer (hvis nogle) i system;

|Lager System|
:Modtager mål fra sælger;
:Beregner styklisten;
:Sender styklisten til sælger;

|Sælger|
:Udarbejder tilbud manuelt;

|Carport Shop|
:Modtager tilbud;
:Sender tilbud til kunde;

|Kunde|
:Modtager tilbud;
:Accepterer tilbud;

|Sælger|
:Modtager accept;
:Opretter ordre manuelt;

|Carport Shop|
:Sender ordrebekræftelse;

|Kunde|
:Modtager ordrebekræftelse;
stop
@enduml
